eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8500/eureka/
spring:
  application:
    name: eureka-client
server:
  port: 10010
---
spring:
  profiles: instance2 
server:
  port: 10012
  